[package]
name = "generator"
version = "0.1.0"
edition = "2021"
description = "Data generator for accounting benchmark"

[dependencies]
chrono = "0.4"
rand = "0.8"
clap = { version = "4.4", features = ["derive"] }
polars = { version = "0.35", features = ["lazy", "parquet"] }
