[package]
name = "accounting_benchmark"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
rand = "0.8"
csv = "1.1"
polars = { version = "0.46.0", features = ["lazy", "csv", "dtype-datetime","temporal","strings"] }
